name: Build Firefox for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hours
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev \
          build-essential cmake libpulse-dev libdbus-glib-1-dev \
          libx11-dev libxext-dev libxrender-dev libxt-dev libxft-dev \
          libgtk-3-dev libglib2.0-dev libpango1.0-dev libfontconfig1-dev \
          yasm libasound2-dev libcurl4-openssl-dev \
          libnss3-dev libnss3 git curl autoconf2.13

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Clone Firefox repository
        run: |
          git clone --depth 1 https://github.com/mozilla-firefox/firefox firefox-source
      
      - name: Configure build
        working-directory: firefox-source
        run: |
          # Create mozconfig file
          echo "# Build Firefox for Linux" > mozconfig
          echo "ac_add_options --enable-application=browser" >> mozconfig
          echo "ac_add_options --enable-optimize" >> mozconfig
          echo "ac_add_options --disable-debug" >> mozconfig
          echo "ac_add_options --enable-release" >> mozconfig
          echo "ac_add_options --disable-tests" >> mozconfig
          echo "mk_add_options MOZ_MAKE_FLAGS=\"-j$(nproc)\"" >> mozconfig
      
      - name: Bootstrap build environment
        working-directory: firefox-source
        run: |
          ./mach --no-interactive bootstrap --application-choice=browser
      
      - name: Build Firefox
        working-directory: firefox-source
        run: |
          ./mach build
      
      - name: Package Firefox
        working-directory: firefox-source
        run: |
          ./mach package
      
      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: firefox-linux
          path: |
            firefox-source/obj-*/dist/firefox-*.tar.bz2
            firefox-source/obj-*/dist/firefox-*.tar.gz
            firefox-source/obj-*/dist/firefox-*.tar.xz
          if-no-files-found: warn
