name: Build Firefox for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hours
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        shell: pwsh
        run: |
          choco install -y wget 7zip
          python -m pip install --upgrade pip
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-msvc
          override: true
          components: rustfmt, clippy
          target: x86_64-pc-windows-msvc

      - name: Install Git for Windows SDK
        uses: git-for-windows/setup-git-for-windows-sdk
        with:
          flavor: full
    
      - name: Install Windows SDK
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          #version-sdk: 26100
          features: 'OptionId.WindowsPerformanceToolkit,OptionId.WindowsDesktopDebuggers,OptionId.AvrfExternal,OptionId.NetFxSoftwareDevelopmentKit,OptionId.WindowsSoftwareLogoToolkit,OptionId.IpOverUsb,OptionId.MSIInstallTools,OptionId.SigningTools,OptionId.UWPManaged,OptionId.UWPCPP,OptionId.UWPLocalized,OptionId.DesktopCPPx86,OptionId.DesktopCPPx64,OptionId.DesktopCPParm64'

      - name: Install MozillaBuild
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe -OutFile MozillaBuild.exe
          Start-Process -FilePath .\MozillaBuild.exe -ArgumentList '/S' -Wait

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process -FilePath .\vs_buildtools.exe -ArgumentList '--quiet', '--wait', '--norestart', '--nocache', '--add Microsoft.VisualStudio.Workload.VCTools', '--add Microsoft.VisualStudio.Component.VC.ATL', '--add Microsoft.VisualStudio.Component.VC.ATLMFC' -Wait
  
      - name: Clone Firefox repository
        shell: pwsh
        run: |
          git clone --depth 1 https://github.com/mozilla-firefox/firefox firefox-source
      
      - name: Configure build
        shell: pwsh
        working-directory: firefox-source
        run: |
          @"
          # Build Firefox for Windows
          ac_add_options --enable-application=browser
          ac_add_options --enable-optimize
          ac_add_options --disable-debug
          ac_add_options --enable-release
          ac_add_options --disable-tests
          ac_add_options --target=x86_64-pc-mingw32
          "@ | Out-File -FilePath mozconfig -Encoding ASCII
      
      - name: Bootstrap build environment
        shell: pwsh
        working-directory: firefox-source
        run: |
          python ./mach --no-interactive bootstrap --application-choice=browser
      
      - name: Build Firefox
        shell: cmd
        working-directory: firefox-source
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          python ./mach build
      
      - name: Package Firefox
        shell: cmd
        working-directory: firefox-source
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          python ./mach package
      
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: firefox-windows
          path: |
            firefox-source/obj-*/dist/firefox-*.zip
            firefox-source/obj-*/dist/firefox-*.exe
          if-no-files-found: warn
